import matplotlib.pyplot as plt
import numpy as np

x = np.arange(1, 44) 

sns.set_theme(style="ticks")
fig = plt.figure(figsize=(18, 12))

ax = fig.add_axes([0.1, 0.1, 0.4, 0.2])
for i in range(len(x)):
    ax.plot([x[i], x[i]], [wsl_dif_370[i], wsl_dif_585[i]], color='k', linestyle='-',zorder=0)
ax.scatter(x, wsl_dif_370[:], color='blue', label='SSP3-7.0',zorder=1)
ax.scatter(x, wsl_dif_585[:], color='red', label='SSP5-8.5',zorder=1)
ax.set_ylim(-50,220)
ax.set_xlim(0,43.5)
ax.set_xticks([4.25,12,17.5,23.5,33,41])
ax.set_xticklabels(['NA','SA','EU','AF','AS','OC'],fontsize=20)
ax.tick_params(axis='y', labelsize=20) 
ax.legend(fontsize=18)
sns.despine(ax=ax, left=False, right=True, top=True, bottom=False) 
ax.spines["left"].set_linewidth(1.5) 
ax.spines["left"].set_color("black")
ax.spines["bottom"].set_linewidth(1.5) 
ax.spines["bottom"].set_color("black")
ax.set_xlabel("Regions",fontsize=24)
ax.set_ylabel("Avoidable growth (%)",fontsize=22)
plt.axvspan(-2, 8.5, color='lightcoral', alpha=0.2)
plt.axvspan(8.5,15.5, color='lightblue', alpha=0.2)
plt.axvspan(15.5,19.5, color='lightcoral', alpha=0.2)
plt.axvspan(19.5,27.5, color='lightblue', alpha=0.2)
plt.axvspan(27.5,38.5, color='lightcoral', alpha=0.2)
plt.axvspan(38.5,43.5, color='lightblue', alpha=0.2)
ax.set_title('e. ESL',fontsize=22,fontweight='bold',loc='left')


ax = fig.add_axes([0.6, 0.1, 0.4, 0.2])
for i in range(len(x)):
    ax.plot([x[i], x[i]], [eba_dif_370[i], eba_dif_585[i]], color='k', linestyle='-',zorder=0)
ax.scatter(x, eba_dif_370[:], color='blue', label='Group A',zorder=1)
ax.scatter(x, eba_dif_585[:], color='red', label='Group B',zorder=1)
ax.set_ylim(-50,100)
ax.set_xlim(0,43.5)
ax.set_xticks([4.25,12,17.5,23.5,33,41])
ax.set_xticklabels(['NA','SA','EU','AF','AS','OC'],fontsize=20)
ax.tick_params(axis='y', labelsize=20) 
sns.despine(ax=ax, left=False, right=True, top=True, bottom=False) 
ax.spines["left"].set_linewidth(1.5) 
ax.spines["left"].set_color("black")
ax.spines["bottom"].set_linewidth(1.5) 
ax.spines["bottom"].set_color("black")
plt.axvspan(-2, 8.5, color='lightcoral', alpha=0.2)
plt.axvspan(8.5,15.5, color='lightblue', alpha=0.2)
plt.axvspan(15.5,19.5, color='lightcoral', alpha=0.2)
plt.axvspan(19.5,27.5, color='lightblue', alpha=0.2)
plt.axvspan(27.5,38.5, color='lightcoral', alpha=0.2)
plt.axvspan(38.5,43.5, color='lightblue', alpha=0.2)
ax.set_xlabel("Regions",fontsize=24)
ax.set_title('f. EBA',fontsize=22,fontweight='bold',loc='left')

plt.show()